"""initial

Revision ID: 0b44fcccc097
Revises: 3e0261dd6dcc
Create Date: 2023-08-22 14:19:26.231606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b44fcccc097'
down_revision = '3e0261dd6dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waiter', sa.Column('account_id', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waiter', 'account_id')
    # ### end Alembic commands ###
