"""initial

Revision ID: 3a7845929afe
Revises: 0b44fcccc097
Create Date: 2023-08-22 14:43:28.062794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a7845929afe'
down_revision = '0b44fcccc097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cook', 'password')
    op.add_column('waiter', sa.Column('email', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waiter', 'email')
    op.add_column('cook', sa.Column('password', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
