"""initial

Revision ID: 3e0261dd6dcc
Revises: 
Create Date: 2023-08-22 14:18:59.471486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e0261dd6dcc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waiter', 'account_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waiter', sa.Column('account_id', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
