"""Initial migration.

Revision ID: 4e66e0002bbb
Revises: c3fff22b3ef7
Create Date: 2023-08-21 15:42:17.466418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e66e0002bbb'
down_revision = 'c3fff22b3ef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'admin', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin', type_='unique')
    # ### end Alembic commands ###
